theme: jekyll-theme-hacker
title: Welcome to the webpage for the perfect number calculator. 
description: Feel free to email me at g$hirodkar at hotmail + ".com". (Be sure to replace the "$" with "s" to avoid spam and "at" with "@".)

